modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "vendingblock"
version = "${version}"
displayName = "Vending Block: Restocked"
authors = "Furglitch"
description = '''
A revival of the classic Vending Block mod!
'''
logoFile = "pack.png"

[[dependencies.vendingblock]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vendingblock]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vendingblock]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
